### ISSUE TITLE
SNDINFO parser incompatibility

### ISSUE THREAD

**Issue by coelckers** [nashmuhandes/GZDoom-GPL#3]
GZDoom-GPL removes "FMOD" from this line of code in s_advsound.h:

else if (sc.Compare("fmod") || sc.Compare("sndsys")) devset.device = MDEV_SNDSYS;

This will cause a parser incompatibility, if some mod actually uses that keyword. Since there is no dependency on FMod here this should be restored.

**Comment by nashmuhandes** [comment]
Done, thanks for this!
